name: Build and Test
on: 
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - main
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install and Build 🔧
        run: |
          npm ci
          npm audit
          npm run lint
          npm test
          npm run build